### ISSUE TITLE
qsub execution fail

### ISSUE THREAD

**Issue by dyt811** [CobraLab/MAGeTDocker#2]
Hi, @gdevenyi , 

After Mb init with some subjects from public and privately available T2 MRI data coregistered and converted to minc, we encountered this error suggesting some dependencies are missing in the Docker image replicated across multiple containers. The docker image was pulled from DockerHub very recently without any modification and started based on the read.me of this repo. It should be up to date. Please let us know if there is a newer MAGeTDocker version or best recommended fix for this. Thanks. We can also provided the test data set via PM if you need them.  

![image](https://user-images.githubusercontent.com/6720068/44692148-94b6e880-aa2f-11e8-86c3-46209ec23175.png)

**Comment by gdevenyi** [comment]
mb run defaults to qbatch job submission.

Try mb run --q parallel.

Having said that, this was mostly a one-off hasn't been updated in quite a while.

Please see https://github.com/cobralab/antsRegistration-MAGet
or the BIDSified version at
https://github.com/BIDS-Apps/MAGeTbrain

**Comment by dyt811** [comment]
Thanks, Gabriel. I found more information from an earlier reply you gave in https://github.com/CobraLab/MAGeTbrain/issues/46. All is well and we will try Niagara/SciNet soon.
