### ISSUE TITLE
MAGeTDocker Voting Stage Issue

### ISSUE THREAD

**Issue by dyt811** [CoBrALab/MAGeTDocker#3]
Hi @gdevenyi ,

We have been able to successfully execute the registration stage but the subsequent voting stage seems to fail. Is this another issue related with QSub system requirement? 

![image](https://user-images.githubusercontent.com/6720068/45038055-7142fd80-b02e-11e8-9d43-737b3c2e52be.png)

The command used to run the voting stage was "mb run vote --q parallel".

**Comment by gdevenyi** [comment]
That error is clearly from GNU parallel saying that things it ran are failing.

1) Do you have enough resources assigned to this? It is very memory hungry. 
2) Try ``mb run vote -q parallel -n`` to list commands and run one manually to see if there are any errors.

This docker is very out of date and unmaintained. I'm not sure how much time I have to support this.

**Comment by gdevenyi** [comment]
No reply. Closing.
