### ISSUE TITLE
 "mb": executable file not found in $PATH

### ISSUE THREAD

**Issue by egeiter-miac** [CoBrALab/MAGeTDocker#4]
Dear Cobralab team

I wanted to test-run MAGeTbrain (MAGeTDocker) as singularity container on my CentOS 7 workstation and ran into the error written in the title. 
Here is what I did:
- Install docker, singularity and qbatch
- Build the singularity container:
`$ singularity build maget1.sif docker://gdevenyi/magetdocker:latest`
- Run the "mb-container" script as described in the README file:
`$ ./mb-container maget1.sif init`

I got the simple error message:  `FATAL:   "mb": executable file not found in $PATH`

Thank you for your help.
Best
emanuel

**Comment by gdevenyi** [comment]
Hi, this is no longer the case, the instructions were to use a different tag of the docker hub. The latest tag also been updated to point to a new build.

**Comment by egeiter-miac** [comment]
You are right, I was using the wrong docker hub tag.
Now it worked with the one you sent me via email.
Thank you.
