### ISSUE TITLE
error in installing the ITK5

### ISSUE THREAD

**Issue by neer86upadhyay** [CoBrALab/MAGeTDocker#5]
Dear Gabriel, 
As per your suggestions, I tried to build the docker using the code available in this repository. by implementing the following commands:
> git clone https://github.com/CobraLab/MAGeTDocker.git
> cd MAGeTDocker
> docker build -t magetdocker .

After running the code, I got issues related with the installing of ITK5 due to error in the created source path of GitHub given below:
. #17 8.685 [2/17] Performing download step (git clone) for 'ITKv5'
#17 8.685 FAILED: ITKv5-prefix/src/ITKv5-stamp/ITKv5-download 
#17 8.685 cd /opt/ANTs/build && /usr/bin/cmake -P /opt/ANTs/build/ITKv5-prefix/tmp/ITKv5-gitclone.cmake && /usr/bin/cmake -E touch /opt/ANTs/build/ITKv5-prefix/src/ITKv5-stamp/ITKv5-download
#17 8.685 Cloning into 'ITKv5'...
#17 8.685 fatal: unable to connect to github.com:
#17 8.685 github.com[0: 140.82.121.4]: errno=Connection refused
#17 8.685 
#17 8.685 Cloning into 'ITKv5'...
#17 8.685 fatal: unable to connect to github.com:
#17 8.685 github.com[0: 140.82.121.4]: errno=Connection refused
#17 8.685 
#17 8.685 Cloning into 'ITKv5'...
#17 8.685 fatal: unable to connect to github.com:
#17 8.685 github.com[0: 140.82.121.4]: errno=Connection refused
#17 8.685 
#17 8.685 -- Had to git clone more than once:
#17 8.685           3 times.
#17 8.685 CMake Error at ITKv5-prefix/tmp/ITKv5-gitclone.cmake:31 (message):
#17 8.685   Failed to clone repository:
#17 8.685   **'git://github.com/InsightSoftwareConsortium/ITK.git'**

Could you please help me in sorting this issue out. I also checked the docker file to edit but it is just building the ITK5 from the ANTS super build source( No direct path to GitHub directory of ITK5 have been passed).

Best Regards, 
Neeraj

**Comment by gdevenyi** [comment]
The error here is clear, your network is either broken or unstable and unable to connect to github from within the container.
```
#17 8.685 fatal: unable to connect to github.com:
#17 8.685 github.com[0: 140.82.121.4]: errno=Connection refused
```

An already built container is available on dockerhub https://hub.docker.com/r/gdevenyi/magetdocker
