### ISSUE TITLE
Error in running Magetbrain using Docker

### ISSUE THREAD

**Issue by neer86upadhyay** [CoBrALab/MAGeTDocker#6]
Dear Gabriel, 
I pulled the magetbrain:latest image using docker and than tried to run the Magetbrain on my local workstation using the attached commands but even though after copying the label and brains in the atlas. it's nor recognising the brain files for the concerned label files in the atlas folder inside input directory. 

Could you please help in sorting this issue. 

Please have look at the attached [image.](<img width="914" alt="Bildschirmfoto 2021-04-30 um 12 01 41" src="https://user-images.githubusercontent.com/7860814/116697440-7a452200-a9c3-11eb-8bb9-bc0e374d1dbd.png">)

Best Regards

**Comment by gdevenyi** [comment]
In order to provide any support, you will need to provide the exact steps you did, as well as all output from any commands.

**Comment by neer86upadhyay** [comment]
This already ran so I am closing the issue.
